---
# tasks file for Test
- name: Add a label
  k8s:
    state: present
    definition:
      apiVersion: v1alpha1
      kind: Test
      metadata:
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        labels:
          my-label: "foo"
  register: after_label

- name: What did we get?
  debug:
    msg: "{{ after_label }}"
